access_key_manager/access_key_manager/urls.py
from django.contrib import admin
from django.urls import path,include
from authentication import views

urlpatterns = [
    path('',views.home_view, name='home'),
    path('admin/', admin.site.urls),
    path('', include('schoolapp.urls')),
    path('', include('authentication.urls')),
    path('', include('adminapp.urls')),
]

access_key_manager/adminapp/urls.py
from django.urls import path
from adminapp import views
from .views import AccessKeyListView
from .apiviews import GetActiveAccessKey

app_name = 'adminapp'

urlpatterns = [
    path('feed/', AccessKeyListView.as_view(), name='access_key_list'),
    path('generate/<int:school_id>/', views.access_key_generate, name='access_key_generate'),
    path('update/<int:access_key_id>/', views.access_key_update, name='access_key_update'),
    path('revoke/<int:access_key_id>/', views.revoke_key, name='access_key_revoke'),
    path('acess_key_info/', GetActiveAccessKey.as_view(), name='access_key_info'),
    
]

access_key_manager/authentication/urls.py
from django.urls import path
from authentication import views
from authentication.views import SignUpView


app_name = 'authentication'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='account_activation'),
    path('reset/<uidb64>/<token>/', views.reset_password_confirm, name='password_reset_confirm'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset/done/', views.password_reset_done, name='password_reset_done'),
]

access_key_manager/adminapp/models.py
from django.db import models
from authentication.models import CustomUser

class AccessKey(models.Model):
    ACTIVE = 'active'
    EXPIRED = 'expired'
    REVOKED = 'revoked'
    STATUS_CHOICES = [
        (ACTIVE, 'Active'),
        (EXPIRED, 'Expired'),
        (REVOKED, 'Revoked'),
    ]
    
    key = models.CharField(max_length=64, unique=True)
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default=ACTIVE)
    date_of_procurement = models.DateField(auto_now_add=True)
    expiry_date = models.DateField()
    school = models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True,blank=True)

access_key_manager/adminapp/forms.py
from django import forms
from django.utils import timezone
import datetime
from authentication.models import CustomUser
from .models import AccessKey
import random,string


class AccessKeyForm(forms.ModelForm):
    class Meta:
        model = AccessKey
        fields = ['expiry_date']

    def save(self, commit=True):
        access_key = super().save(commit=False)
        access_key.key = self.generate_key()
        access_key.expiry_date = self.cleaned_data['expiry_date']
       
        if commit:
            access_key.save()
        return access_key

    def generate_key(self):
        # Generate a random 64-character string for the key
        return ''.join(random.choices(string.ascii_uppercase + string.ascii_lowercase + string.digits, k=32))
    
class EmailForm(forms.Form):
    email = forms.EmailField(max_length=200)

access_key_manager/adminapp/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import AccessKey
# from schoolapp.models import School
from .forms import AccessKeyForm
from django.contrib import messages
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
import datetime
from authentication.models import CustomUser


@method_decorator(login_required, name='dispatch')
class AccessKeyListView(ListView):
    model = AccessKey
    template_name = 'adminapp/dashboard.html'
    context_object_name = 'access_keys'
    ordering = ['date_of_procurement']
    paginate_by = 10


@login_required
def access_key_generate(request,school_id):
    user = request.user
    school_id = user.id
    schools =user.school_name
    form = AccessKeyForm()
   
    
    if request.method == 'POST':
        form = AccessKeyForm(request.POST)
        if form.is_valid():
            access_key = form.save(commit=False)
            
            # access_key.key = form.generate_key()
            access_key.school = user
            if access_key.expiry_date and access_key.expiry_date < datetime.date.today():
                messages.warning(request,'Expiry date cannot be in the past.')
                return redirect('adminapp:access_key_generate',user.id)
            else:
                access_key.expiry_date = form.cleaned_data['expiry_date']
            access_key.save()
            
            current_site = get_current_site(request)
            access_key = AccessKey.objects.filter(school_id=school_id, status='active').first()
            
            
            message=render_to_string('message.html', {
                'user': user,
                'domain': current_site.domain,
                'access_key':access_key,
                'schools':schools
            })
       
            message = strip_tags(message)
            mail_subject = 'Access key Purchase'
            email_from = user.email
            recipient_list =["douglasdanso66@gmail.com"]
            send_mail( mail_subject, message, email_from, recipient_list )
            return redirect('schoolapp:access_key_list', user.id)
        else:
            form = AccessKeyForm()
    context = {
        'form':form,
        'schools':schools,
    }  
    
    return render(request, 'adminapp/access_key_generate.html', context)

@login_required
def revoke_key(request, access_key_id):
    access_key = get_object_or_404(AccessKey, id=access_key_id)
    access_key.status = 'revoked'
    access_key.save()
    messages.success(request, 'Key revoked successfully.')
    return redirect('adminapp:access_key_list')

@login_required
def access_key_update(request, access_key_id):
    access_key = get_object_or_404(AccessKey, pk=access_key_id)

    if request.method == 'POST':
        form = AccessKeyForm(request.POST, instance=access_key)
        if form.is_valid():
            if access_key.expiry_date and access_key.expiry_date < datetime.date.today():
                messages.warning(request,'Expiry date cannot be in the past.')
                return redirect('adminapp:access_key_update',access_key.id)
            else:
                access_key.expiry_date = form.cleaned_data['expiry_date']
            access_key = form.save()
            
            messages.success(request, f'Access key {access_key.key} has been updated.')
            return redirect('adminapp:access_key_list')
    else:
        form = AccessKeyForm(instance=access_key)

    return render(request, 'adminapp/access_key_update.html', {'form': form, 'access_key': access_key})

access_key_manager/adminapp/templates/adminapp/access_key_generate.html
 {% block content %}
<h1>Generate Access Key</h1>

{% if access_key %}
<p>New access key generated: {{ access_key.key }}</p>
{% endif %}

<form method="post">
    {% csrf_token %}


    <label for="expiry_date">Expiry Date:</label>
    <input type="date" name="expiry_date" id="expiry_date" required><br><br>

    <input type="submit" value="Generate Access Key">
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %}<b> "{{ message.tags }}:"</b>{% endif %} {{ message }}</li>
    {% endfor %}
</ul>
{% endif %} {% endblock %}

access_key_manager/adminapp/templates/adminapp/access_key_list.html
<!-- access_key_list.html -->
{% extends 'adminapp/base.html' %}

{% block content %}
  <h2>Access Keys</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Key</th>
        <th>Status</th>
        <th>Date of Procurement</th>
        <th>Expiry Date</th>
        {% if user.is_staff %}
          <th>Actions</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for access_key in object_list %}
        <tr>
          <td>{{ access_key.key }}</td>
          <td>{{ access_key.status }}</td>
          <td>{{ access_key.date_of_procurement }}</td>
          <td>{{ access_key.expiry_date }}</td>
          {% if user.is_staff %}
            <td>
              <a href="{% url 'access_key_update' access_key.pk %}">Update</a>
            </td>
          {% endif %}
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No access keys found.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

access_key_manager/adminapp/templates/adminapp/access_key_update.html
{% extends "adminapp/base.html" %}

{% block content %}
  <h1>Update Access Key</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Access Key</button>
  </form>
 {% if access_key.status == 'active' %}
  <a href="{% url 'adminapp:access_key_revoke' access_key.id %}">Revoke</a> 
{% endif %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{% if message.tags %}<b> "{{ message.tags }}:"</b>{% endif %} {{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

access_key_manager/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Key Manager{% endblock %}</title>
</head>

<body>
    <nav>
        <ul>
            <li><a href="{% url 'adminapp:access_key_list' %}">Access Keys</a></li>
            {% comment %}
            <li><a href="{% url 'adminapp:access_key_generate' school.id %}">Generate Access Key</a></li> {% endcomment %}
        </ul>
    </nav>
    <main>
        {% block content %} {% endblock %}
    </main>
</body>

access_key_manager/adminapp/templates/adminapp/dashboard.html
 {% extends 'adminapp/base.html' %} {% block content %}
<h4><a href="{% url 'authentication:logout'%}"> Logout</a></h4>
<h2>Access Keys</h2>
<table class="table">
    <thead>
        <tr>
            <th>School</th>
            <th>Key</th>
            <th>Status</th>
            <th>Date of Procurement</th>
            <th>Expiry Date</th>

            <th>Actions</th>

        </tr>
    </thead>
    <tbody>
        {% for access_key in object_list %}
        <tr>
            <td>{{ access_key.school }}</td>
            <td>{{ access_key.key }}</td>
            <td>{{ access_key.status }}</td>
            <td>{{ access_key.date_of_procurement }}</td>
            <td>{{ access_key.expiry_date }}</td>
            {% if access_key.status != 'revoked'%}
            <td>
                <a href="{% url 'adminapp:access_key_update' access_key.pk %}">Update</a>
            </td>
            {% else %}
            <td>
                No Action
            </td>

            {% endif %}
        </tr>

        {% empty %}
        <tr>
            <td colspan="5">No access keys found.</td>
        </tr>
        {% endfor %}

    </tbody>
</table>
<h2><a href="{% url 'adminapp:access_key_info' %}">Get access key api</a></h2>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %}<b> "{{ message.tags }}:"</b>{% endif %} {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span> {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a> {% endif %}
    </span>
</div>

{% endblock %}

access_key_manager/adminapp/templates/adminapp/email_api_form.html
{% block content %}
  <h1>Enter your email address</h1>
  <form method="get">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}