access_key_manager/access_key_manager/urls.py
from django.contrib import admin
from django.urls import path,include
from authentication import views

urlpatterns = [
    path('',views.home_view, name='home'),
    path('admin/', admin.site.urls),
    path('', include('schoolapp.urls')),
    path('', include('authentication.urls')),
    path('', include('adminapp.urls')),
]

access_key_manager/adminapp/urls.py
from django.urls import path
from adminapp import views
from .views import AccessKeyListView
from .apiviews import GetActiveAccessKey

app_name = 'adminapp'

urlpatterns = [
    path('feed/', AccessKeyListView.as_view(), name='access_key_list'),
    path('generate/<int:school_id>/', views.access_key_generate, name='access_key_generate'),
    path('update/<int:access_key_id>/', views.access_key_update, name='access_key_update'),
    path('revoke/<int:access_key_id>/', views.revoke_key, name='access_key_revoke'),
    path('acess_key_info/', GetActiveAccessKey.as_view(), name='access_key_info'),
    
]

access_key_manager/authentication/urls.py
from django.urls import path
from authentication import views
from authentication.views import SignUpView


app_name = 'authentication'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='account_activation'),
    path('reset/<uidb64>/<token>/', views.reset_password_confirm, name='password_reset_confirm'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset/done/', views.password_reset_done, name='password_reset_done'),
]

access_key_manager/schoolapp/urls.py
from django.urls import path

from schoolapp import views
app_name = 'schoolapp'

urlpatterns = [
    path('access-keys/<int:school_id>/',views.access_key_list, name='access_key_list'),
    # path('school/', views.school_view, name='school'),
    path('purchase/<int:school_id>/', views.purchase_key, name='purchase_key'),
    
] 

access_key_manager/schoolapp/models.py
# from django.db import models
# from django.conf import settings
# from authentication.models import CustomUser

# class School(models.Model):
#     school_name= models.CharField(max_length=100)
#     user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    

access_key_manager/schoolapp/forms.py
# from django import forms
# # from .models import School
# from authentication.models import CustomUser
# from adminapp.models import AccessKey
# from django.shortcuts import get_object_or_404


# class SchoolForm(forms.ModelForm):
#    pass
   

access_key_manager/schoolapp/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from adminapp.models import AccessKey
# from .models import School
# from .forms import SchoolForm
from django.core.paginator import Paginator
from authentication.models import CustomUser

@login_required
def access_key_list(request,school_id):
    
    user = request.user 
    school_id =user.id
    school = user.school_name
    access_keys = AccessKey.objects.filter(school_id=school_id).order_by('-date_of_procurement')
    paginator = Paginator(access_keys, 20) 
   



    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = { 'access_keys': access_keys,
               'school': school,
                'user': user,
                'page_obj':page_obj,
                }
    return render(request, 'access_key_list.html',context) 

@login_required
def purchase_key(request,school_id):

    user = request.user 
    school_id = user.id
    # school = user.school_name
    active_key = AccessKey.objects.filter(school_id = school_id, status=AccessKey.ACTIVE)
    if active_key:
        messages.warning(request, 'you already have an active access key')
        return redirect('schoolapp:access_key_list',user.id)
    else:
        return redirect('adminapp:access_key_generate',user.id)
    

# @login_required
# def school_view(request):
#     form = SchoolForm()

#     if request.method == 'POST':
#         form = SchoolForm(request.POST)
#         if form.is_valid():
#             name=form.cleaned_data['school_name']
#             user = request.user
#             school = School.objects.create(school_name=name, user=user)
#             school.save()
#             return redirect('schoolapp:access_key_list', school_id=school.id)
#         else:
#             form = SchoolForm()

    # return render(request, 'school.html', {'form':form})

access_key_manager/schoolapp/templates/access_key_list.html
{% block content %}
<h4><a href="{% url 'authentication:logout'%}"> Logout</a></h4>
<h1>Access Keys</h1>



<h3>welcome, {{school}}</h3>
{% for access_key in page_obj %} {% if access_key.status == 'active' %}

<p>Your active access key: {{ access_key.key }}</p>
<p>expiry date : {{ access_key.expiry_date }}</p>
{% endif %} {% endfor %}

<h2>Access Key History</h2>
<table class="table">
    <thead>
        <tr>

            <th>Key</th>
            <th>Status</th>
            <th>Date of Procurement</th>
            <th>Expiry Date</th>
        </tr>
    </thead>
    <tbody>
        {% for access_key in page_obj %}

        <tr>

            <td>{{ access_key.key }}</td>
            <td>{{ access_key.status }}</td>
            <td>{{ access_key.date_of_procurement }}</td>
            <td>{{ access_key.expiry_date }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<button><a href="{% url 'schoolapp:purchase_key' user.id%}"> Request Access Key</a></button> {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %}<b> "{{ message.tags }}:"</b>{% endif %} {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="pagination">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">previous</a> {% endif %}

    <span class="current-page">{{ page_obj.number }}</span> {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a> {% endif %}
</div>
{% endblock %}

access_key_manager/schoolapp/templates/message.html
<html>

<body>
    <p>Dear Micro Focus admin</p>
    <p>{{ user.email}} from {{user.school_name}} has generated an access key, {{access_key.key}} with expiry date, {{access_key.expiry_date}}</p>
</body>

access_key_manager/schoolapp/templates/school.html
<html>
    <head>
        <title>Register School</title>
    </head>
    <body>
        <h2>Hello {{user.email}}, please enter the name of your school to register</h2>
        <form method = "POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" name="register">Register</a>
                </button>
        </form>
    </body>
</html>